### ISSUE TITLE
Hi from WPExplorer

### ISSUE THREAD

**Issue by wpexplorer** [oceanwp/ocean#1]
Hey there, this is AJ. I see you've been making some great changes to make the theme "yours" and it's looking much better! It looks like you aren't quite done yet because a lot of the code is very much the same as the Total theme. If you have any questions or want some help with something, let me know here and I'll be happy to help.

For example, It looks like you may be using Redux for the meta now (great) but Redux has a built-in theme panel and customizer - so why not use Redux for your theme panel and Customizer settings as well and remove the files inspired by Total? If you are using Redux for the metaboxes it may be better optimized and easier to expand on if you use it for the other parts as well - just a thought ;)

Additionally if you are going to continue using a lot of the same functions as Total such as those found here - https://github.com/oceanwp/ocean/blob/master/inc/helpers.php (it seems you just renamed core-functions.php to helpers.php) - I would really appreciate at least a mention on the functions that have been taken from Total. Example:

<pre>
/**
 * Returns post video HTML
 *
 * @since 1.0.0
 * @link    http://wpexplorer-themes.com/total/
 */
function ocean_get_post_video_html( $video = '' ) {
}
</pre>

While you have been making some nice changes, the general functionality of the theme and how it works (function.php. classes, widgets, global_obj) a lot of it works just like the Total theme. If you are a developer then you should plan out how YOU want your theme to work and code it in that manner rather then relying on the way in which the Total theme has been designed. I hope that makes sense.

For example, do you understand the main purpose of this Class? - https://github.com/oceanwp/ocean/blob/master/inc/classes/object.php - for your theme you really should just turn this class into functions and place them each into helpers.php because you don't need to have this whole separate class in your theme ;)

Another example is this - https://github.com/oceanwp/ocean/blob/master/inc/classes/breadcrumbs.php - which was taken from the Total theme and actually I have completely recoded it since there are several issues. You should consider maybe creating your own class or just use the standard Yoast breadcrumbs. Or you can switch the code for better code from a free GPL plugin like this one: https://wordpress.org/plugins/breadcrumb-trail/ (created by the same guy helping you out I believe)

Let me know if you do have any questions I am happy to help. I was too busy the last 2 weeks but if you have any questions I can help you out for sure. Just let me know - I will follow the github repo.

- AJ

**Comment by oceanwp** [comment]
Hello, thank you for your message, sorry for my late reply but I have not received any notification from github, I just saw your message.

For the Ocean Settings meta box, I only need options that I set, I have not found a simple code with tabs for doing this, but if you do not want me to use this code, I will try to find another way.
For the gallery meta box, I use a github code.
I do not use redux because I will post the theme on wordpress.org and it is forbidden to include a panel, everything must be done through the customizer.

For helpers file, I put your link directly on top of the file, tell me if it's ok for you.

For the class object, I put the functions into the helpers.php file.

For the breadcrumbs, thank you so much, I could not find on github :)

Tell me if everything is ok for you, have a good day :)

**Comment by wpexplorer** [comment]
Cool. I'll look through this in a bit.

I wanted to point this product out - https://generatepress.com/ - it's a free GPL project on WordPress.org. You may want to have a look if you aren't able to make your own framework from scratch. Oceanwp is looking better, but it still has so much code and ideas from the original Total theme :( Maybe you can get some better inspiration from a full free GPL theme?

**Comment by oceanwp** [comment]
Hello, I took your free Elegant theme as framework and I put a link "@link http://wpexplorer-themes.com/total/" as you asked me for some functions but tell me if you want that I replace a particular function.
Thank you :)

**Comment by oceanwp** [comment]
Hello, if everything is good for you, I close this topic.
We can continue to discuss, I will answer as soon as possible.
Have a very nice day :)
