### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by borisiceman** [oceanwp/ocean#2]
There is a place where to read changelog?

**Comment by oceanwp** [comment]
Hello, sorry for this, what I use to update the theme automatically in the WordPress dashboard does not allow to display changelogs.

You can see them in two ways,
1. Via github: [changelog](https://github.com/oceanwp/ocean/blob/master/changelog.md)
2. Via FTP, you upload the "changelog.md" file to your computer, this file is in the folder of the theme.
